In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
gt = pd.read_csv('/content/drive/MyDrive/globalterrorismdb_0718dist.csv',encoding='ISO-8859-1')
gt.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


eventid  iyear  imonth  iday approxdate  extended resolution  country  \
0  197000000001   1970       7     2        NaN         0        NaN       58   
1  197000000002   1970       0     0        NaN         0        NaN      130   
2  197001000001   1970       1     0        NaN         0        NaN      160   
3  197001000002   1970       1     0        NaN         0        NaN       78   
4  197001000003   1970       1     0        NaN         0        NaN      101   

          country_txt  region  ... addnotes scite1 scite2  scite3  dbsource  \
0  Dominican Republic       2  ...      NaN    NaN    NaN     NaN      PGIS   
1              Mexico       1  ...      NaN    NaN    NaN     NaN      PGIS   
2         Philippines       5  ...      NaN    NaN    NaN     NaN      PGIS   
3              Greece       8  ...      NaN    NaN    NaN     NaN      PGIS   
4               Japan       4  ...      NaN    NaN    NaN     NaN      PGIS   

   INT_LOG  INT_IDEO INT_MISC INT_ANY  related  
0        0         0        0       0      NaN  
1        0         1        1       1      NaN  
2       -9        -9        1       1      NaN  
3       -9        -9        1       1      NaN  
4       -9        -9        1       1      NaN  

[5 rows x 135 columns]

In [ ]:
gt.shape

(181691, 135)

In [ ]:
gt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Columns: 135 entries, eventid to related
dtypes: float64(55), int64(22), object(58)
memory usage: 187.1+ MB


In [ ]:
gt.describe(include=object)

approxdate resolution country_txt  \
count                    9239       2220      181691   
unique                   2244       1859         205   
top     September 18-24, 2016   8/4/1998        Iraq   
freq                      101         18       24636   

                        region_txt provstate     city  \
count                       181691    181270   181257   
unique                          12      2855    36674   
top     Middle East & North Africa   Baghdad  Unknown   
freq                         50474      7645     9775   

                                                location  \
count                                              55495   
unique                                             44109   
top     The attack took place in Baghdad, Baghdad, Iraq.   
freq                                                 142   

                                                  summary  \
count                                              115562   
unique                                             112492   
top     09/00/2016: Sometime between September 18, 201...   
freq                                                  100   

                   alternative_txt    attacktype1_txt  ...   divert  \
count                        29011             181691  ...      324   
unique                           5                  9  ...      143   
top     Insurgency/Guerilla Action  Bombing/Explosion  ...  Unknown   
freq                         23410              88255  ...       27   

       kidhijcountry ransomnote hostkidoutcome_txt  \
count           3305        514              10991   
unique           217        387                  7   
top         Colombia          0            Unknown   
freq             687         36               3606   

                                                 addnotes  \
count                                               28289   
unique                                              15429   
top     Casualty numbers for this incident conflict ac...   
freq                                                 1607   

                                                   scite1  \
count                                              115500   
unique                                              83988   
top     Committee on Government Operations United Stat...   
freq                                                  205   

                                                   scite2  \
count                                               76933   
unique                                              62263   
top     Christopher Hewitt, "Political Violence and Te...   
freq                                                  134   

                                                   scite3  \
count                                               43516   
unique                                              36090   
top     Christopher Hewitt, "Political Violence and Te...   
freq                                                  139   

                        dbsource  \
count                     181691   
unique                        26   
top     START Primary Collection   
freq                       78002   

                                                  related  
count                                               25038  
unique                                              14306  
top     201612010023, 201612010024, 201612010025, 2016...  
freq                                                   80  

[4 rows x 58 columns]

In [ ]:
gt['iyear'].value_counts()

2014    16903
2015    14965
2016    13587
2013    12036
2017    10900
2012     8522
2011     5076
1992     5071
2010     4826
2008     4805
2009     4721
1991     4683
1989     4324
1990     3887
1988     3721
1984     3495
1994     3456
2007     3242
1997     3197
1987     3183
1995     3081
1996     3058
1985     2915
1983     2870
1986     2860
2006     2758
1979     2662
1980     2662
1981     2586
1982     2544
2005     2017
2001     1906
2000     1814
1978     1526
1999     1395
2002     1333
1977     1319
2003     1278
2004     1166
1998      934
1976      923
1975      740
1970      651
1974      581
1972      568
1973      473
1971      471
Name: iyear, dtype: int64

In [ ]:
gt['country_txt'].value_counts()

Iraq                   24636
Pakistan               14368
Afghanistan            12731
India                  11960
Colombia                8306
                       ...  
International              1
Wallis and Futuna          1
South Vietnam              1
Andorra                    1
Antigua and Barbuda        1
Name: country_txt, Length: 205, dtype: int64

In [ ]:
gt['attacktype1_txt'].value_counts()

Bombing/Explosion                      88255
Armed Assault                          42669
Assassination                          19312
Hostage Taking (Kidnapping)            11158
Facility/Infrastructure Attack         10356
Unknown                                 7276
Unarmed Assault                         1015
Hostage Taking (Barricade Incident)      991
Hijacking                                659
Name: attacktype1_txt, dtype: int64

In [ ]:
gt['targtype1_txt'].value_counts()

Private Citizens & Property       43511
Military                          27984
Police                            24506
Government (General)              21283
Business                          20669
Transportation                     6799
Utilities                          6023
Unknown                            5898
Religious Figures/Institutions     4440
Educational Institution            4322
Government (Diplomatic)            3573
Terrorists/Non-State Militia       3039
Journalists & Media                2948
Violent Political Party            1866
Airports & Aircraft                1343
Telecommunication                  1009
NGO                                 970
Tourists                            440
Maritime                            351
Food or Water Supply                317
Abortion Related                    263
Other                               137
Name: targtype1_txt, dtype: int64

In [ ]:
gt['gname'].value_counts()

Unknown                                             82782
Taliban                                              7478
Islamic State of Iraq and the Levant (ISIL)          5613
Shining Path (SL)                                    4555
Farabundo Marti National Liberation Front (FMLN)     3351
                                                    ...  
Ansar Sarallah                                          1
Sword of Islam                                          1
Support of Ocalan-The Hawks of Thrace                   1
Arab Revolutionary Front                                1
MANO-D                                                  1
Name: gname, Length: 3537, dtype: int64

In [ ]:
gt['weaptype1_txt'].value_counts()

Explosives                                                                     92426
Firearms                                                                       58524
Unknown                                                                        15157
Incendiary                                                                     11135
Melee                                                                           3655
Chemical                                                                         321
Sabotage Equipment                                                               141
Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)      136
Other                                                                            114
Biological                                                                        35
Fake Weapons                                                                      33
Radiological                                                     

In [ ]:
gt[pd.isnull(gt['approxdate'])]
gt.isnull().sum()

eventid            0
iyear              0
imonth             0
iday               0
approxdate    172452
               ...  
INT_LOG            0
INT_IDEO           0
INT_MISC           0
INT_ANY            0
related       156653
Length: 135, dtype: int64

In [ ]:
gt.select_dtypes(exclude='number').describe()

approxdate resolution country_txt  \
count                    9239       2220      181691   
unique                   2244       1859         205   
top     September 18-24, 2016   8/4/1998        Iraq   
freq                      101         18       24636   

                        region_txt provstate     city  \
count                       181691    181270   181257   
unique                          12      2855    36674   
top     Middle East & North Africa   Baghdad  Unknown   
freq                         50474      7645     9775   

                                                location  \
count                                              55495   
unique                                             44109   
top     The attack took place in Baghdad, Baghdad, Iraq.   
freq                                                 142   

                                                  summary  \
count                                              115562   
unique                                             112492   
top     09/00/2016: Sometime between September 18, 201...   
freq                                                  100   

                   alternative_txt    attacktype1_txt  ...   divert  \
count                        29011             181691  ...      324   
unique                           5                  9  ...      143   
top     Insurgency/Guerilla Action  Bombing/Explosion  ...  Unknown   
freq                         23410              88255  ...       27   

       kidhijcountry ransomnote hostkidoutcome_txt  \
count           3305        514              10991   
unique           217        387                  7   
top         Colombia          0            Unknown   
freq             687         36               3606   

                                                 addnotes  \
count                                               28289   
unique                                              15429   
top     Casualty numbers for this incident conflict ac...   
freq                                                 1607   

                                                   scite1  \
count                                              115500   
unique                                              83988   
top     Committee on Government Operations United Stat...   
freq                                                  205   

                                                   scite2  \
count                                               76933   
unique                                              62263   
top     Christopher Hewitt, "Political Violence and Te...   
freq                                                  134   

                                                   scite3  \
count                                               43516   
unique                                              36090   
top     Christopher Hewitt, "Political Violence and Te...   
freq                                                  139   

                        dbsource  \
count                     181691   
unique                        26   
top     START Primary Collection   
freq                       78002   

                                                  related  
count                                               25038  
unique                                              14306  
top     201612010023, 201612010024, 201612010025, 2016...  
freq                                                   80  

[4 rows x 58 columns]

In [ ]:
gt.dtypes

eventid        int64
iyear          int64
imonth         int64
iday           int64
approxdate    object
               ...  
INT_LOG        int64
INT_IDEO       int64
INT_MISC       int64
INT_ANY        int64
related       object
Length: 135, dtype: object

In [ ]:
for column in gt:
    print(gt[column])

In [ ]:
gt["approxdate"] = gt.approxdate.fillna("Not known")
gt.approxdate.unique()

array(['Not known', 'January 19-20, 1970', 'February 6-9, 1970', ...,
       '2017-12-29 00:00:00', 'December 25, 2017-January 5, 2018',
       '2017-12-31 00:00:00'], dtype=object)

In [ ]:
gt.approxdate.isnull().sum()

0

In [ ]:
gt.select_dtypes(include="number").isnull().sum()


eventid      0
iyear        0
imonth       0
iday         0
extended     0
            ..
nreleased    0
INT_LOG      0
INT_IDEO     0
INT_MISC     0
INT_ANY      0
Length: 77, dtype: int64

In [ ]:
gt["nreleased"] = gt.nreleased.fillna(0)
gt.nreleased.unique()

array([ 0.000e+00,  1.000e+00,  5.000e+00,  6.000e+01,  1.000e+01,
        1.550e+02,  1.750e+02,  3.000e+00,  4.000e+00,  6.000e+00,
        2.600e+01,  1.870e+02,  1.050e+02,  2.000e+00,  8.200e+01,
        1.300e+01,  4.800e+01, -9.900e+01,  1.600e+01,  8.000e+00,
        2.300e+01,  2.500e+01,  9.200e+01,  7.000e+00,  1.200e+01,
        7.000e+01,  5.600e+01,  1.400e+01,  3.400e+01,  6.600e+01,
        4.400e+01,  3.000e+01,  1.370e+02,  1.800e+01,  1.100e+02,
        1.470e+02,  4.300e+01,  5.000e+01,  5.400e+01,  1.130e+02,
        2.150e+02,  7.900e+01,  3.800e+01,  1.020e+02,  1.380e+02,
        1.000e+02,  9.000e+01,  9.000e+00,  2.100e+01,  1.140e+02,
        3.900e+02,  1.890e+02,  2.640e+02,  4.600e+01,  1.180e+02,
        1.310e+02,  1.270e+02,  1.570e+02,  3.300e+01,  9.700e+01,
        7.100e+01,  1.610e+02,  1.520e+02,  2.200e+01,  1.250e+02,
        1.510e+02,  1.290e+02,  4.200e+01,  3.100e+01,  3.200e+01,
        1.620e+02,  8.800e+01,  1.440e+02,  1.150e+02,  1.900e

In [ ]:
gt.nreleased.isnull().sum()

0

In [ ]:
gt.select_dtypes(include="number").isnull().sum().sort_values().head(60)

In [ ]:
gt["doubtterr"] = gt.doubtterr.fillna(0)
gt.doubtterr.unique()

array([ 0., -9.,  1.])

In [ ]:
gt["ishostkid"] = gt.ishostkid.fillna(0)
gt.ishostkid.unique()

array([ 0.,  1., -9.])

In [ ]:
gt["natlty1"] = gt.natlty1.fillna(0)
gt.natlty1.unique()

array([  58.,   21.,  217.,  218.,   75.,  216.,  222.,  163.,   97.,
         15.,  199.,  102.,   65.,  185.,    0.,  101.,  422.,   60.,
        158.,  359.,   96.,   11.,  160.,   44.,  155.,  999.,  233.,
         30.,   87.,  183.,  162.,   45.,   78.,  145.,   93.,  235.,
         98.,  403.,   99.,   94.,   38.,  161.,  198.,  209.,   49.,
        167.,   95.,   51.,   69.,  120.,  229.,  142.,   43.,   89.,
        228.,  130.,  200.,   92.,  144.,  174.,    6.,  159.,  236.,
        173.,   55.,  362.,   17.,   26.,   61.,   29.,   83.,  110.,
        149.,    5.,  184.,  603.,  153.,  104.,   53.,  156.,  186.,
         59.,  121.,  136.,  182.,  147.,  139.,   12.,   20.,  106.,
        137.,   86.,  201.,  208.,  138.,  207.,  128.,   32.,  205.,
         18.,   68.,  223.,  215.,  124.,   14.,  231.,  230.,    8.,
        151.,  100.,  213.,   50.,  111.,  203.,   84.,   67.,   56.,
        113.,   63.,    4.,   88.,  604.,  123.,   19.,   80.,  220.,
         22.,  377.,

In [ ]:
gt["latitude"] = gt.latitude.fillna(0)
gt.latitude.unique()

array([18.456792, 19.371887, 15.478598, ...,  2.359673, 35.407278,
        6.900742])

In [ ]:
gt["multiple"] = gt.multiple.fillna(0)
gt.multiple.unique()

array([0., 1.])

In [ ]:
gt["specificity"] = gt.specificity.fillna(0)
gt.specificity.unique()

array([1., 4., 5., 2., 3., 0.])

In [ ]:
gt["guncertain1"] = gt.guncertain1.fillna(0)
gt.guncertain1.unique()

array([0., 1.])

In [ ]:
gt=gt.apply(lambda x: x.fillna(0) if x.dtype.kind in 'biufc' else x.fillna('.'))

In [ ]:
gt.select_dtypes(exclude='number').columns

Index(['approxdate', 'resolution', 'country_txt', 'region_txt', 'provstate',
       'city', 'location', 'summary', 'alternative_txt', 'attacktype1_txt',
       'attacktype2_txt', 'attacktype3_txt', 'targtype1_txt',
       'targsubtype1_txt', 'corp1', 'target1', 'natlty1_txt', 'targtype2_txt',
       'targsubtype2_txt', 'corp2', 'target2', 'natlty2_txt', 'targtype3_txt',
       'targsubtype3_txt', 'corp3', 'target3', 'natlty3_txt', 'gname',
       'gsubname', 'gname2', 'gsubname2', 'gname3', 'gsubname3', 'motive',
       'claimmode_txt', 'claimmode2_txt', 'claimmode3_txt', 'weaptype1_txt',
       'weapsubtype1_txt', 'weaptype2_txt', 'weapsubtype2_txt',
       'weaptype3_txt', 'weapsubtype3_txt', 'weaptype4_txt',
       'weapsubtype4_txt', 'weapdetail', 'propextent_txt', 'propcomment',
       'divert', 'kidhijcountry', 'ransomnote', 'hostkidoutcome_txt',
       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'related'],
      dtype='object')

In [ ]:
gt['resolution']=gt['resolution'].map(lambda x : x.replace(".","Unknown"))
gt['country_txt']=gt['country_txt'].map(lambda x : x.replace(".","Unknown"))
gt['provstate']=gt['provstate'].map(lambda x : x.replace(".","Unknown"))
gt['city']=gt['city'].map(lambda x : x.replace("Unknown",""))
gt['location']=gt['location'].map(lambda x : x.replace(".","Unknown"))
gt['summary']=gt['summary'].map(lambda x : x.replace(".","-Blank-"))
gt['alternative_txt']=gt['alternative_txt'].map(lambda x : x.replace(".","-Blank-"))
gt['attacktype2_txt']=gt['attacktype2_txt'].map(lambda x : x.replace(".","-Blank-"))
gt['attacktype3_txt']=gt['attacktype3_txt'].map(lambda x : x.replace(".","-Blank-"))
gt['corp1']=gt['corp1'].map(lambda x : x.replace(".","Unknown"))
gt['target1']=gt['target1'].map(lambda x : x.replace(".","Unknown"))
gt['natlty1_txt']=gt['natlty1_txt'].map(lambda x : x.replace(".","Unknown"))
gt['targtype2_txt']=gt['targtype2_txt'].map(lambda x : x.replace(".","-Blank-"))
gt['targsubtype2_txt']=gt['targsubtype2_txt'].map(lambda x : x.replace(".","-Blank-"))
gt['corp2']=gt['corp2'].map(lambda x : x.replace(".","Unknown"))
gt['target2']=gt['target2'].map(lambda x : x.replace(".","Unknown"))
gt['natlty2_txt']=gt['natlty2_txt'].map(lambda x : x.replace(".","Unknown"))
gt['targtype3_txt']=gt['targtype3_txt'].map(lambda x : x.replace(".","Unknown"))
gt['targsubtype3_txt']=gt['targsubtype3_txt'].map(lambda x : x.replace(".","Unknown"))
gt['corp3']=gt['corp3'].map(lambda x : x.replace(".","Unknown"))
gt['target3']=gt['target3'].map(lambda x : x.replace(".","Unknown"))
gt['natlty3_txt']=gt['natlty3_txt'].map(lambda x : x.replace(".","Unknown"))
gt['gsubname']=gt['gsubname'].map(lambda x : x.replace(".","Unknown"))
gt['gname2']=gt['gname2'].map(lambda x : x.replace(".","Unknown"))
gt['gsubname2']=gt['gsubname2'].map(lambda x : x.replace(".","Unknown"))
gt['gname3']=gt['gname3'].map(lambda x : x.replace(".","Unknown"))
gt['gsubname3']=gt['gsubname3'].map(lambda x : x.replace(".","Unknown"))
gt['motive']=gt['motive'].map(lambda x : x.replace(".","Unknown"))
gt['claimmode_txt']=gt['claimmode_txt'].map(lambda x : x.replace(".","Unknown"))
gt['claimmode2_txt']=gt['claimmode2_txt'].map(lambda x : x.replace(".","Unknown"))
gt['claimmode3_txt']=gt['claimmode3_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weapsubtype1_txt']=gt['weapsubtype1_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weaptype2_txt']=gt['weaptype2_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weapsubtype2_txt']=gt['weapsubtype2_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weaptype3_txt']=gt['weaptype3_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weapsubtype3_txt']=gt['weapsubtype3_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weaptype4_txt']=gt['weaptype4_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weapsubtype4_txt']=gt['weapsubtype4_txt'].map(lambda x : x.replace(".","Unknown"))
gt['weapdetail']=gt['weapdetail'].map(lambda x : x.replace(".","Unknown"))
gt['propextent_txt']=gt['propextent_txt'].map(lambda x : x.replace(".","Unknown"))
gt['propcomment']=gt['propcomment'].map(lambda x : x.replace(".","-Blank-"))
gt['divert']=gt['divert'].map(lambda x : x.replace(".","Unknown"))
gt['kidhijcountry']=gt['kidhijcountry'].map(lambda x : x.replace(".","Unknown"))
gt['ransomnote']=gt['ransomnote'].map(lambda x : x.replace(".","-Blank-"))
gt['hostkidoutcome_txt']=gt['hostkidoutcome_txt'].map(lambda x : x.replace(".","Unknown"))
gt['addnotes']=gt['addnotes'].map(lambda x : x.replace(".","-Blank-"))
gt['related']=gt['related'].map(lambda x : x.replace(".","-Blank-"))

In [ ]:
gt.related.unique()

array(['-Blank-', '197001300001, 197001300002',
       '197002030001, 197002030002', ...,
       '201712290022, 201712290023, 201712290024',
       '201712290031, 201712290032', '201712300005, 201712310002'],
      dtype=object)

In [ ]:
gt.head()

eventid  iyear  imonth  iday approxdate  extended resolution  country  \
0  197000000001   1970       7     2  Not known         0    Unknown       58   
1  197000000002   1970       0     0  Not known         0    Unknown      130   
2  197001000001   1970       1     0  Not known         0    Unknown      160   
3  197001000002   1970       1     0  Not known         0    Unknown       78   
4  197001000003   1970       1     0  Not known         0    Unknown      101   

          country_txt  region  ... addnotes scite1 scite2  scite3  dbsource  \
0  Dominican Republic       2  ...  -Blank-      .      .       .      PGIS   
1              Mexico       1  ...  -Blank-      .      .       .      PGIS   
2         Philippines       5  ...  -Blank-      .      .       .      PGIS   
3              Greece       8  ...  -Blank-      .      .       .      PGIS   
4               Japan       4  ...  -Blank-      .      .       .      PGIS   

   INT_LOG  INT_IDEO INT_MISC INT_ANY  related  
0        0         0        0       0  -Blank-  
1        0         1        1       1  -Blank-  
2       -9        -9        1       1  -Blank-  
3       -9        -9        1       1  -Blank-  
4       -9        -9        1       1  -Blank-  

[5 rows x 135 columns]

In [ ]:
print("Country with the most attacks : ",gt.country_txt.value_counts().idxmax())
print("City with the most attacks : ",gt.city.value_counts().idxmax())
print("Region with the most attacks : ",gt.region_txt.value_counts().idxmax())


Country with the most attacks :  Iraq
City with the most attacks :  
Region with the most attacks :  Middle East & North Africa


In [ ]:
gt['city']=gt['city'].map(lambda x : x.replace("Unknown",""))

In [ ]:
gt.city.unique()

array(['Santo Domingo', 'Mexico city', '', ..., 'Hungrum',
       'Ceelka Geelow', 'Kubentog'], dtype=object)

In [ ]:
gt.isnull.mean().sort_values(ascending=False)